### ISSUE TITLE
Update to TailwindCSS v3

### ISSUE THREAD

**Issue by surjithctly** [edjw/find-nearest-tailwind-colour#1]
First of all, I can't say how many times I have opened this little tool myself. It was really helpful to find matching colors in Tailwind. Thanks for making this tool :)

Now, TailwindCSS is to be updated to v3 and the alpha is already available. Can you port it to v3 now so it will be ready as soon as the v3 will be released to the public? 

The main changes are there are no more extended colors and color names have changed. 
For more info see this PR from Adam Wathan: https://github.com/tailwindlabs/tailwindcss/pull/5384

Thanks so much!

**Comment by edjw** [comment]
Hi, great to hear it's been useful. It's nearly a year since I looked at this project. I'm going to take a look at what would be involved to have a v3 version. From a very brief look, it looks a lot simpler with v3 than v2 so I'm hopeful this won't be a big job

**Comment by surjithctly** [comment]
FYI, v3 is now released and it's the stable version.

**Comment by edjw** [comment]
@surjithctly I've just added a beta version for v3 here: [https://v3--find-nearest-tailwind-colour.netlify.app](https://v3--find-nearest-tailwind-colour.netlify.app)

Would you mind checking that it's working as you'd expect? I haven't used v3 of Tailwind at all so I'm not 100% confident I'd recognise any issues. 

Also, is this tool useful any more now that you can set arbitrary values in square brackets and just have tailwind's compiler do it all?

**Comment by surjithctly** [comment]
Looks good to me 👍

It is useful because I prefer to use Tailwind Color when a closest #HEX matches, otherwise I will use the custom color.  So I usually look them to see if there are any matching color without too much difference.

**Comment by edjw** [comment]
I've made v3 the standard now
