### ISSUE TITLE
Suggestion: Specify Tailwind version(s)

### ISSUE THREAD

**Issue by kalnode** [edjw/find-nearest-tailwind-colour#6]
Hey, great tool!

However it suggested some colors unavailable in my TW version: "slate-100", "neutral-900", etc. After some digging I realized these are TW3 colors.

Perhaps on your app's page, specify the TW version(s) your tool works for.

thx

**Comment by edjw** [comment]
Hi, yep this used to just have the v2 colours, and then I had both alongside each other for a while, and then I just did the v3 colours. I can add a v2 colours option

**Comment by edjw** [comment]
Closed in favour of #9
